import type { Bike, Testimonial } from './types';

export const bikes: Bike[] = [
  // Scooters
  {
    id: 1,
    name: 'Dio Red DLX',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://www.panalmotors.com/images/dio/dio-dlx-red.png',
    description: 'A stylish and reliable scooter, perfect for navigating city streets with ease and comfort. Great fuel efficiency.',
  },
  {
    id: 2,
    name: 'Dio Blue',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://www.honda2wheelersindia.com/assets/images/dioImages/color/Dapper-Blue-Metallic.png',
    description: 'A stylish and reliable scooter, perfect for navigating city streets with ease and comfort. Great fuel efficiency.',
  },
  {
    id: 3,
    name: 'Dio Full Blue',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://bd.gaadicdn.com/processedimages/honda/dio/source/dio62e8eec2e6f47.jpg?tr=w-375',
    description: 'A stylish and reliable scooter, perfect for navigating city streets with ease and comfort. Great fuel efficiency.',
  },
  {
    id: 4,
    name: 'Dio Red',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://hondabikes.goodshow.com.ua/images/bikes/honda_dio_2020/colors/01.png',
    description: 'A stylish and reliable scooter, perfect for navigating city streets with ease and comfort. Great fuel efficiency.',
  },
  {
    id: 5,
    name: 'Dio Black',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://bd.gaadicdn.com/processedimages/honda/dio/source/dio62e8eebe1c55c.jpg?tr=w-375',
    description: 'A stylish and reliable scooter, perfect for navigating city streets with ease and comfort. Great fuel efficiency.',
  },
  {
    id: 6,
    name: 'Activa 6G Blue',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://activa.honda2wheelersindia.com/assets/images/color/Pearl-Siren-Blue-New.png',
    description: 'A popular and dependable scooter, known for its smooth ride and comfortable seating. Ideal for daily commutes.',
  },
  {
    id: 7,
    name: 'Activa 6G Grey',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://www.eshasuzuki.com/wp-content/uploads/2023/04/Mat-Axis-Grey-Metallic-New.png',
    description: 'A popular and dependable scooter, known for its smooth ride and comfortable seating. Ideal for daily commutes.',
  },
  {
    id: 8,
    name: 'Aviator DLX Red',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://www.sagmart.com/uploads/2016/10/26/product_1/honda_aviator_red.png',
    description: 'A premium scooter with a classy look and comfortable ride. Perfect for making a statement on the road.',
  },
  {
    id: 9,
    name: 'Pleasure Grey',
    type: 'Scooter',
    brand: 'Hero',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://bd.gaadicdn.com/processedimages/hero/pleasure-plus/source/pleasure-plus62e8f17a94d93.jpg?tr=w-375',
    description: 'A lightweight and easy-to-handle scooter, designed for convenience and style in urban settings.',
  },
  // Geared Bike
  {
    id: 10,
    name: 'Honda CD 110 (Gear)',
    type: 'Geared Bike',
    brand: 'Honda',
    pricePerHour: 60,
    pricePerDay: 600,
    image: 'https://www.honda2wheelersindia.com/assets/images/cd110/color/color-black-with-red.png',
    description: 'A reliable geared motorcycle offering a balance of power and fuel economy. Great for both city and highway rides.',
  },
];

export const testimonials: Testimonial[] = [];
