import type { Bike, Testimonial } from './types';

export const bikes: Bike[] = [
  // Scooters
  {
    id: 1,
    name: 'Dio Red DLX',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://tse1.mm.bing.net/th/id/OIP.TDzs4pYiNfZGdO4EmEf0ZgHaFj',
    description: 'A stylish and reliable scooter, perfect for navigating city streets with ease and comfort. Great fuel efficiency.',
  },
  {
    id: 2,
    name: 'Dio Blue',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://tse2.mm.bing.net/th/id/OIP.kLVjR9kPox7sIGlLIF2u3QHaFj',
    description: 'A stylish and reliable scooter, perfect for navigating city streets with ease and comfort. Great fuel efficiency.',
  },
  {
    id: 3,
    name: 'Dio Full Blue',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://bd.gaadicdn.com/processedimages/honda/dio-bs6/640X309/dio-bs664883818de8e8.jpg?imwidth=890&impolicy=resize',
    description: 'A stylish and reliable scooter, perfect for navigating city streets with ease and comfort. Great fuel efficiency.',
  },
  {
    id: 4,
    name: 'Dio Red',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://th.bing.com/th/id/R.93d837b09829fbe1c3ebf50685bba01d?rik=zWDJ36tejPF8lg&riu=http%3a%2f%2fic1.maxabout.us%2fautos%2ftw_india%2f2%2f2017%2f3%2f2017-honda-dio.jpg',
    description: 'A stylish and reliable scooter, perfect for navigating city streets with ease and comfort. Great fuel efficiency.',
  },
  {
    id: 5,
    name: 'Dio Black',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://tse3.mm.bing.net/th/id/OIP.GI2ixePenHmFS88ElsfAZAHaEK',
    description: 'A stylish and reliable scooter, perfect for navigating city streets with ease and comfort. Great fuel efficiency.',
  },
  {
    id: 6,
    name: 'Activa 6G Blue',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://tse1.mm.bing.net/th/id/OIP.CLHCiGz9nZtkD9UH3bCKPQAAAA',
    description: 'A popular and dependable scooter, known for its smooth ride and comfortable seating. Ideal for daily commutes.',
  },
  {
    id: 7,
    name: 'Activa 6G Grey',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://bd.gaadicdn.com/processedimages/honda/activa-125-2019/source/activa-125-20196422c410ade55.jpg',
    description: 'A popular and dependable scooter, known for its smooth ride and comfortable seating. Ideal for daily commutes.',
  },
  {
    id: 8,
    name: 'Aviator DLX Red',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://www.sagmart.com/uploads/2016/10/26/product_1/honda_aviator_red.png',
    description: 'A premium scooter with a classy look and comfortable ride. Perfect for making a statement on the road.',
  },
  {
    id: 9,
    name: 'Pleasure Grey',
    type: 'Scooter',
    brand: 'Hero',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://images.91wheels.com/assets/b_images/gallery/heromotocorp/pleasure/heromotocorp-pleasure-7-1598109388.png',
    description: 'A lightweight and easy-to-handle scooter, designed for convenience and style in urban settings.',
  },
  // Geared Bike
  {
    id: 10,
    name: 'Honda CD 110 (Gear)',
    type: 'Geared Bike',
    brand: 'Honda',
    pricePerHour: 60,
    pricePerDay: 600,
    image: 'https://awtobazar.in/wp-content/uploads/2019/11/CD-110-Dream-DLX-3.png',
    description: 'A reliable geared motorcycle offering a balance of power and fuel economy. Great for both city and highway rides.',
  },
];

export const testimonials: Testimonial[] = [];
