import type { Bike, Testimonial } from './types';

export const bikes: Bike[] = [
  // Scooters
  {
    id: 1,
    name: 'Dio Red DLX',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://placehold.co/600x400.png',
    description: 'A stylish and reliable scooter, perfect for navigating city streets with ease and comfort. Great fuel efficiency.',
  },
  {
    id: 2,
    name: 'Dio Blue',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://placehold.co/600x400.png',
    description: 'A stylish and reliable scooter, perfect for navigating city streets with ease and comfort. Great fuel efficiency.',
  },
  {
    id: 3,
    name: 'Dio Full Blue',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://placehold.co/600x400.png',
    description: 'A stylish and reliable scooter, perfect for navigating city streets with ease and comfort. Great fuel efficiency.',
  },
  {
    id: 4,
    name: 'Dio Red',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://placehold.co/600x400.png',
    description: 'A stylish and reliable scooter, perfect for navigating city streets with ease and comfort. Great fuel efficiency.',
  },
  {
    id: 5,
    name: 'Dio Black',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://placehold.co/600x400.png',
    description: 'A stylish and reliable scooter, perfect for navigating city streets with ease and comfort. Great fuel efficiency.',
  },
  {
    id: 6,
    name: 'Activa 6G Blue',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://placehold.co/600x400.png',
    description: 'A popular and dependable scooter, known for its smooth ride and comfortable seating. Ideal for daily commutes.',
  },
  {
    id: 7,
    name: 'Activa 6G Grey',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://placehold.co/600x400.png',
    description: 'A popular and dependable scooter, known for its smooth ride and comfortable seating. Ideal for daily commutes.',
  },
  {
    id: 8,
    name: 'Aviator DLX Red',
    type: 'Scooter',
    brand: 'Honda',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://placehold.co/600x400.png',
    description: 'A premium scooter with a classy look and comfortable ride. Perfect for making a statement on the road.',
  },
  {
    id: 9,
    name: 'Pleasure Grey',
    type: 'Scooter',
    brand: 'Hero',
    pricePerHour: 40,
    pricePerDay: 400,
    image: 'https://placehold.co/600x400.png',
    description: 'A lightweight and easy-to-handle scooter, designed for convenience and style in urban settings.',
  },
  // Geared Bike
  {
    id: 10,
    name: 'Honda CD 110 (Gear)',
    type: 'Geared Bike',
    brand: 'Honda',
    pricePerHour: 60,
    pricePerDay: 600,
    image: 'https://placehold.co/600x400.png',
    description: 'A reliable geared motorcycle offering a balance of power and fuel economy. Great for both city and highway rides.',
  },
];

export const testimonials: Testimonial[] = [];
